name: CI

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Unit Tests
        run: |
          docker compose run --rm unit-tests
          ls -R CardValidation.Tests.Unit/TestResults || true

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: CardValidation.Tests.Unit/TestResults

      - name: Report Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: CardValidation.Tests.Unit/TestResults/*.trx
          reporter: dotnet-trx

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Integration Tests (with web service)
        run: |
          docker compose up --build --abort-on-container-exit integration-tests web
          ls -R CardValidation.Tests.Integration/TestResults || true

      - name: Upload Integration Test Results
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: CardValidation.Tests.Integration/TestResults

      - name: Report Integration Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration Tests
          path: CardValidation.Tests.Integration/TestResults/*.trx
          reporter: dotnet-trx